[package]
name = "hid"
version = "0.1.0"
authors = ["PitchBlackNights <pitchblacknights@proton.me>"]
edition = "2024"

[dependencies]
# hidapi = "2.6"
rusb = "0.9"
windows = { version = "0.61", features = ["Win32_System_Threading"] }
